### ISSUE TITLE
Understanding lcm message delays in drake systems.

### ISSUE THREAD

**Issue by pangtao22** [RobotLocomotion/robot-plan-runner#29]
In our drake systems implementation of `PlanManager`, we have observed a delay on the order of milliseconds between receiving a IIWA_STATUS message and sending a IIWA_COMMAND message. We would like to better understand the reason for this delay @RussTedrake. 

To isolate the delay introduced by the systems framework from our implementation of `StateMachine`, [`IiwaPlanManagerSystem`](https://github.com/RobotLocomotion/robot-plan-runner/blob/2dda9211faf5b3c5210b8092351eda957c20bc09/src/plan_manager_system/iiwa_plan_manager_system.cc#L12) is simplified to a passthough, which only [copies the utime field of the status message into the command message, and then sends it](https://github.com/RobotLocomotion/robot-plan-runner/blob/2dda9211faf5b3c5210b8092351eda957c20bc09/src/plan_manager_system/iiwa_plan_manager_system.cc#L32). 

Time delay between an IIWA_STATUS message and IIWA_COMMAND message is measured as follows:
1. Start `mock_station_simulation` and [`run_plan_manager_system`](https://github.com/RobotLocomotion/robot-plan-runner/blob/2dda9211faf5b3c5210b8092351eda957c20bc09/src/run_plan_manager_system.cc).
2. Start `lcm-logger`.
3. In the log, look for `Event`s  corresponding to IIWA_STATUS and IIWA_COMMAND messages, and record `Event.timestamp`.
4. Time delay can be computed as the difference between `Event.timestamp` of an STATUS and COMMAND message pair, in which the two messages have the same `utime`. The script for computing this delay can be found [here](https://github.com/RobotLocomotion/robot-plan-runner/blob/2dda9211faf5b3c5210b8092351eda957c20bc09/src/lcm_delay_analysis.py).

The average time delay of the systems framework varies from run to run, but is usually between 3 and 8 ms, as shown in the plots below.
![image](https://user-images.githubusercontent.com/20274938/118378496-4ad90c80-b5a2-11eb-9d42-f5df4937709c.png)
![image](https://user-images.githubusercontent.com/20274938/118378513-69d79e80-b5a2-11eb-8fe6-2f62fa3d9cc6.png)

In contrast, the average delay of the multi-threaded implementation of `PlanManager` is between 0.1 and 0.2ms.
![image](https://user-images.githubusercontent.com/20274938/118378569-bd49ec80-b5a2-11eb-8fcd-242ebb00f676.png)

All experiments are run on a Mac mini with Big Sur, 6-core 8th gen i7 and 64GB of RAM.

**Comment by RussTedrake** [comment]
This is great!  I'd definitely like to dig into this and resolve it.  I've got one more lecture to prep for Tuesday, but then can spend time working on this with you.


FWIW, I have had one issue for 3 years, but I think it's not getting you in this example?  https://github.com/RobotLocomotion/drake/issues/9894

**Comment by pangtao22** [comment]
I don't think so. As shown in the figure below, the diagram used to measure delays consists only of generic lcm receiver/publisher and a pass-through (`IiwaPlanManagerSystem`).

<img width="1456" alt="image" src="https://user-images.githubusercontent.com/20274938/118416199-74666680-b67c-11eb-8787-5716407a8694.png">

**Comment by pangtao22** [comment]
As discussed in today's meeting, I first tried setting `Simulator`'s real-time rate to 0 [here](https://github.com/RobotLocomotion/robot-plan-runner/blob/2dda9211faf5b3c5210b8092351eda957c20bc09/src/run_plan_manager_system.cc#L18). As a result, the result at which `IIWA_COMMAND` messages are published jumped from 200Hz to >60000Hz. This is clearly a testament to the systems framework's performance, but the numerous command messages flood the operating system's UDP buffer, which causes almost all status messages to be dropped, making it impossible to measure delay between command and status messages. 

It seems that the delay was introduced by using `LcmInterfaceSystem` to schedule publishing events. Following the example suggested by @RussTedrake , i.e. this [issue](https://github.com/RobotLocomotion/drake/pull/11281) and one of its [example implementation](https://github.com/RobotLocomotion/drake/blob/cafccd336b159b9779d62cabbf88ea0d9f00feac/examples/kuka_iiwa_arm/iiwa_controller.cc#L133-L144), we may need to call `diagram.Publish()`manually in a loop upon receiving a `IIWA_STATUS` message. However, running this example, i.e. `//examples/kuka_iiwa_arm/iiwa_controller`, publishes `IIWA_COMMAND` messages at 400Hz instead of 200. 

In contrast, `//examples/kuka_iiwa_arm/kuka_plan_runner`, which doesn't wrap command computation in a `Diagram`, polishes `IIWA_STATUS` messages at 200Hz.

**Comment by RussTedrake** [comment]
If you already have a system in your diagram that will publish on advanceto, then you presumably don't need to call diagram.Publish.  If you have both, that would explain why you end up with 400Hz instead of 200Hz?

**Comment by pangtao22** [comment]
The more straightforward way to implement lcm-driven loop is to have a `diagram` like this:
<img width="867" alt="image" src="https://user-images.githubusercontent.com/20274938/122617445-4b116f80-d05a-11eb-80b5-7ac5867c6b8e.png">,
and call `Simulator.AdvanceTo()` in the loop. Here's the (pseudo)code for this implementation. 

```c++
// owned_lcm_ is a unique pointer to a DrakeLcm instance. 
// diagram is a pointer to the diagram in the figure above.
// plan_manager is a pointer to the `IiwaPlanManagerSystem` in the figure above.

// Create Simulator and extract contexts. 
drake::systems::Simulator<double> sim(*diagram);
auto& context = sim.get_mutable_context();
auto& context_manager = plan_manager_->GetMyMutableContextFromRoot(&context_diagram);

// wait for first IIWA_STATUS message and record its time.
// There also needs to be a subscriber for ROBOT_PLAN, but it's not shown here for brevity.
status_sub = drake::lcm::Subscriber<drake::lcmt_iiwa_status>>(owned_lcm_.get(), "IIWA_STATUS");
drake::lcm::LcmHandleSubscriptionsUntil(
    owned_lcm_.get(), [&]() { return status_sub_->count() > 0; });
const double t_start = status_sub_->message().utime * 1e-6;

while (true) {
    status_sub->clear();

    // Wait for an IIWA_STATUS message.
    drake::lcm::LcmHandleSubscriptionsUntil(
        owned_lcm_.get(), [&]() { return status_sub->count() > 0; });
   
    // Update diagram context.
    plan_manager_->get_iiwa_status_input_port().FixValue(
      &context_manager, status_sub->message()); 

   // Call advance to. 
    const double t = status_sub_->message().utime * 1e-6 - t_start;
    sim.AdvanceTo(t);
}

```

However, scheduling command publishing events with `Simulator` leads to large amounts of duplicate command messages for the same control tick (left blue peak in the figure below), or missed control ticks (right blue peak). 
![image](https://user-images.githubusercontent.com/20274938/122618734-dee43b00-d05c-11eb-9327-5121bf8a5b8f.png)

(There is one control tick every 5ms. So we expect a single peak around 5ms for the time difference between adjacent messages).

**Comment by pangtao22** [comment]
To improve performance and make use of `Simulator`'s event handling, it's better to remove the `LcmPublisherSystem` in the diagram and publish messages manually in the lcm-driven loop, while having `Simulator` handle non-time-critical events such as logging. 

Specifically, here's the new diagram without command publishing:
<img width="618" alt="image" src="https://user-images.githubusercontent.com/20274938/122620406-e574b180-d060-11eb-8804-d037c3d1a940.png">

And here's the (pseudo)code of the lcm-driven loop:
```c++
// owned_lcm_ is a unique pointer to a DrakeLcm instance. 
// diagram is a pointer to the diagram in the figure above.
// plan_manager is a pointer to the `IiwaPlanManagerSystem` in the figure above.

// Create Simulator and extract contexts. 
drake::systems::Simulator<double> sim(*diagram);
auto& context = sim.get_mutable_context();
auto& context_manager = plan_manager_->GetMyMutableContextFromRoot(&context_diagram);

// wait for first IIWA_STATUS message and record its time.
// There also needs to be a subscriber for ROBOT_PLAN, but it's not shown here for brevity.
status_sub = drake::lcm::Subscriber<drake::lcmt_iiwa_status>>(owned_lcm_.get(), "IIWA_STATUS");
drake::lcm::LcmHandleSubscriptionsUntil(
    owned_lcm_.get(), [&]() { return status_sub_->count() > 0; });
const double t_start = status_sub_->message().utime * 1e-6;

while (true) {
    status_sub->clear();

    // Wait for an IIWA_STATUS message.
    drake::lcm::LcmHandleSubscriptionsUntil(
        owned_lcm_.get(), [&]() { return status_sub->count() > 0; });
   
    // Update diagram context.
    plan_manager_->get_iiwa_status_input_port().FixValue(
      &context_manager, status_sub->message()); 

   // Call advance to. 
    const double t = status_sub_->message().utime * 1e-6 - t_start;
    sim.AdvanceTo(t);

    // Compute command message and publish.
    const auto& iiwa_cmd_msg = plan_manager_->get_iiwa_command_output_port()
                            .Eval<drake::lcmt_iiwa_command>(context_manager);
    drake::lcm::Publish(owned_lcm_.get(), "IIWA_COMMAND", iiwa_cmd_msg);

}
```

Now there's only a single peak around 5ms in the time intervals between command messages:
![image](https://user-images.githubusercontent.com/20274938/122620660-882d3000-d061-11eb-829c-a7085a69acee.png)

Moreover, the delay between command and status messages is on par with our implementation that doesn't use `Systems`:
![image](https://user-images.githubusercontent.com/20274938/122620772-cd516200-d061-11eb-8acf-d9a162106bf0.png)

**Comment by pangtao22** [comment]
To conclude, it seems that the performance issue raised at the beginning of this issue is not caused by computing commands by evaluating the `OutputPort` of a `Diagram`, but by `Simulator`'s event scheduling. The solution, is to handle time-critical events such as command publishing manually in an LCM-driven loop, and let `Simulator` handle other events by calling `AdvanceTo` in the loop.

**Comment by RussTedrake** [comment]
Glad it's resolved.  (I suspect that the event system is performant enough, too, but probably harder to use correctly).

**Comment by hjsuh94** [comment]
Been reading the thread a bit late (but with excitement!), but FYI @pangtao22 the images seem broken for me. Will try to infer what they are for now.
