### ISSUE TITLE
Implement config files for settings.

### ISSUE THREAD

**Issue by hjsuh94** [RobotLocomotion/robot-plan-runner#8]
Could model our config file after this:
https://github.com/RobotLocomotion/spartan/blob/854b26e3af75910ef57b874db7853abd4249543e/src/catkin_projects/drake_robot_control/config/iiwa_plan_runner_config.yaml

**Comment by pangtao22** [comment]
Things to put in the config file:
- [Command error checking threshold](https://github.com/RobotLocomotion/robot-plan-runner/blob/9adbf43680ed70ac6274b58bde9ec8848e56cad0/src/state_machine/plan_manager_state_machine.cc#L43)
- [Robot sdf path](https://github.com/RobotLocomotion/robot-plan-runner/blob/9adbf43680ed70ac6274b58bde9ec8848e56cad0/src/plans/iiwa_plan_factory.cc#L18)
- Control period, [here](https://github.com/RobotLocomotion/robot-plan-runner/blob/9adbf43680ed70ac6274b58bde9ec8848e56cad0/src/run_plan_manager_system.cc#L4) and [here](https://github.com/RobotLocomotion/robot-plan-runner/blob/9adbf43680ed70ac6274b58bde9ec8848e56cad0/src/run_plan_manager.cc#L4).

**Comment by hjsuh94** [comment]
Being tracked on #18, most issues are addressed except for the nominal home configuration on DiffIK.

**Comment by hjsuh94** [comment]
Will close the issue since this is implemented in #18.
